// Case #1: try ... catch

const test = ['dummy'];

try {
  console.log('success');
} catch (e) {
  /* @ts-expect-error @rehearsal TODO TS18046: 'e' is of type 'unknown'. */
  console.log(e.message);
  /* @ts-expect-error @rehearsal TODO TS18046: 'e' is of type 'unknown'. */
  console.log(e.notErrorMember);

  /* @ts-expect-error @rehearsal TODO TS18046: 'e' is of type 'unknown'. */
  if (e.name === 'Test') {
    /* @ts-expect-error @rehearsal TODO TS18046: 'e' is of type 'unknown'. */
    console.log(e.name);
    /* @ts-expect-error @rehearsal TODO TS18046: 'e' is of type 'unknown'. */
    console.log(e.name);
    /* @ts-expect-error @rehearsal TODO TS18046: 'e' is of type 'unknown'. */
    console.log(e.name);
    /* @ts-expect-error @rehearsal TODO TS18046: 'e' is of type 'unknown'. */
    console.log(e.name);
  }

  /* @ts-expect-error @rehearsal TODO TS18046: 'e' is of type 'unknown'. */
  if (test[1] === undefined && e.name === 'Test') {
    /* @ts-expect-error @rehearsal TODO TS18046: 'e' is of type 'unknown'. */
    console.log(e.name);
  }
}

// Case #3: not a try catch

function getObject<T>(): T {
  const object = ['dummy'];
  return object as unknown as T;
}

const dummy = getObject();

/* @ts-expect-error @rehearsal TODO TS18046: 'dummy' is of type 'unknown'. */
dummy.key;
